export { default as AuthBackgroundImgae } from "./auth-background.png"
export { default as ProfessorImage } from "./professor-background.png"
export { default as StudentImage } from "./student-background.png"
export { default as ProfessorSignUpImage } from "./ProfessorSignUpImage.png"
export { default as StudentSignUpImage } from "./StudentSignupImage.png"