export { default as AuthBackgroundImgae } from "./auth-background.png"
export { default as ProfessorImage } from "./professor-background.png"
export { default as StudentImage } from "./student-background.png"
export { default as ProfessorSignUpImage } from "./ProfessorSignUpImage.png"
export { default as StudentSignUpImage } from "./StudentSignupImage.png"
export { default as ProfessorProfileImage } from "./professor.jpg"
export { default as StudentProfileImage } from "./student.jpg"
export { default as EditProfessorProfile } from "./editProfessorProfile.jpg"
export { default as ApplicationProcess } from "./application-process.png"
export { default as Verification } from "./verification.png"
export { default as NewPassword } from "./forgotpass3.png"
export { default as CardBackground } from "./card-background.png"
export { default as ProfessorHomePage1} from "./ProfessorHomePage.png"
export { default as ChartImage } from './chart-image.png'
export { default as LandingImage } from './landing-image.png'
export { default as TopUniversitiesImage } from './top-universities-image.png'
export { default as TopStudentsImage } from './top-students-image.png'
export { default as TopProfessorsImage } from './top-professors-image.png'
export { default as StudentHomePage1 } from './StudentHomePage.png'
export { default as ProfessorTimelineImage } from './professor-timeline-image.png'
export { default as StudentTimelineImage } from './student-timeline-image.png'
export { default as WhyusProfessorImage } from './whyus-professor-image.png'
export { default as WhyusStudentImage } from './whyus-student-image.png'
export { default as SlideshowUniversityImage } from './slideshow-university-image.png'
export { default as SlideshowProfessorImage } from './slideshow-professor-image.png'
export { default as SlideshowStudentImage } from './slideshow-student-image.png'
